# Generated by Django 4.2.13 on 2024-07-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='file',
            new_name='file_content',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
