# Generated by Django 4.2.13 on 2024-07-15 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='company_details',
        ),
    ]
